name: Create PR

on:
  issues:
    types: [edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    name: Create PR
    if: "!contains(github.event.comment.body , '[vx.dev]') && github.event.comment.user.type != 'bot'"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.45.2

      - name: generate UI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WHITELIST: ${{ secrets.WHITELIST }}
          CONFIG: ${{ vars.CONFIG }}
          ACTOR: ${{ github.actor }}
        run: deno run --unstable -A prompts/entry.ts

      - name: Commit generated files directly
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: auto-generate UI from issue" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD



